

name: Playwright Test Execution

on:
  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1

      - uses: microsoft/playwright-github-action@v1

      - name: Install dependencies and run tests
        run: npm install && npm test

      - name : Rename videos
        run: |
           for dir in ./videos/*/ 
            do
                dir=${dir%*/}  
                for FILE in "${dir%*/}"/*.webm
                do
                    echo $FILE
                    mv "$FILE" "${dir%*/}/report.webm"
                done
            done
        
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: test-artifacts
          path: |
           report
           videos    
